name: Build APK
on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        command: buildozer android debug
        buildozer_version: master
        
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: KPBTR-App-APK
        path: ${{ steps.buildozer.outputs.filename }}
